import { useState } from 'react'
import { createCalendarEvent, deleteCalendarEvent } from '../service/CalendarEventService'
import { useToast } from '../context/useToast'

export default function CalendarEventManager({ events, onChange }) {
  const [open, setOpen] = useState(false), [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ title: '', eventDate: '', type: 'HOLIDAY', description: '' })
  const { showToast } = useToast()
  async function submit(e) { e.preventDefault(); setSaving(true); try { const response = await createCalendarEvent(form); onChange([...events, response.data]); setForm({ title: '', eventDate: '', type: 'HOLIDAY', description: '' }); setOpen(false); showToast('Calendar event added.', 'success'); } catch { showToast('Could not add this calendar event.', 'error'); } finally { setSaving(false) } }
  async function remove(id) { try { await deleteCalendarEvent(id); onChange(events.filter(event => event.id !== id)); showToast('Calendar event removed.', 'success'); } catch { showToast('Could not remove this calendar event.', 'error') } }
  return <section className="ph-card calendar-manager"><div className="calendar-manager__heading"><div><p className="dashboard-panel__eyebrow">Admin tools</p><h2>Holidays & company events</h2></div><button className="ph-btn ph-btn-primary" onClick={() => setOpen(value => !value)}><i className={`bi bi-${open ? 'x-lg' : 'plus-lg'}`}></i>{open ? 'Close' : 'Add event'}</button></div>{open && <form className="calendar-manager__form" onSubmit={submit}><input className="ph-input" required placeholder="Event title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/><input className="ph-input" required type="date" value={form.eventDate} onChange={e => setForm({ ...form, eventDate: e.target.value })}/><select className="ph-select" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="HOLIDAY">Holiday</option><option value="COMPANY_EVENT">Company event</option></select><input className="ph-input" maxLength="500" placeholder="Optional details" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/><button className="ph-btn ph-btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Save event'}</button></form>}{events.length > 0 && <div className="calendar-manager__list">{events.slice(0, 5).map(event => <div key={event.id}><span title={event.description || event.title}><i className={`bi bi-${event.type === 'HOLIDAY' ? 'calendar-heart' : 'briefcase'}`}></i><strong>{event.title}</strong><small>{new Date(`${event.eventDate}T00:00:00`).toLocaleDateString()}{event.description ? ` · ${event.description}` : ''}</small></span><button aria-label={`Remove ${event.title}`} onClick={() => remove(event.id)}><i className="bi bi-trash3"></i></button></div>)}</div>}</section>
}
