import { useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import '../style/employeeform.css'
import '../style/login-refinement.css'

function Login() {
  const [username,setUsername]=useState(()=>localStorage.getItem('peoplehub_remembered_username')||''),[password,setPassword]=useState(''),[remember,setRemember]=useState(Boolean(localStorage.getItem('peoplehub_remembered_username'))),[show,setShow]=useState(false),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false)
  const {login}=useAuth(),navigate=useNavigate(),location=useLocation()
  async function submit(e){e.preventDefault();setError('');setSubmitting(true);try{const u=await login(username.trim(),password);remember?localStorage.setItem('peoplehub_remembered_username',username.trim()):localStorage.removeItem('peoplehub_remembered_username');navigate(location.state?.from?.pathname||(['ADMIN','HR'].includes(u.role)?'/dashboard':'/'),{replace:true})}catch(err){setError(err?.response?.data?.message||'Invalid username or password.')}finally{setSubmitting(false)}}
  return <main className="login-page"><section className="login-left"><div className="login-brand"><div className="login-brand-copy"><div className="login-logo"><i className="bi bi-buildings-fill"></i></div><h1>People<span>Hub</span></h1><h2>Modern Employee Management Platform</h2><b></b><p>Streamline employee management with a secure, modern and intuitive platform designed for organizations of every size.</p></div><div className="feature-card"><i className="bi bi-people-fill"></i><h3>Core Features</h3><span><i className="bi bi-check2"></i> Employee Records</span><span><i className="bi bi-check2"></i> Department Management</span><span><i className="bi bi-check2"></i> Secure Access</span></div></div></section><section className="login-right"><div className="login-card"><div className="login-heading"><p>WELCOME BACK</p><h2>Welcome Back <span>👋</span></h2><h3>Access your PeopleHub workspace</h3></div>{error&&<div className="login-alert"><i className="bi bi-exclamation-circle-fill"></i>{error}</div>}<form onSubmit={submit}><label className="login-field"><i className="bi bi-person-fill"></i><input autoFocus autoComplete="username" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label className="login-field"><i className="bi bi-lock-fill"></i><input type={show?'text':'password'} autoComplete="current-password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShow(!show)} aria-label="Toggle password"><i className={`bi ${show?'bi-eye-slash-fill':'bi-eye-fill'}`}></i></button></label><label className="remember-me"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Remember my username</label><button className="login-button" disabled={submitting}>{submitting?<><span className="spinner-border spinner-border-sm"></span> Signing in...</>:<><i className="bi bi-box-arrow-in-right"></i> Access Dashboard</>}</button></form><footer>© {new Date().getFullYear()} <strong>PeopleHub</strong><small>Modern Employee Management System</small></footer></div></section></main>
}
export default Login
